![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [1]:
import numpy as np
np.__version__

'2.2.4'

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [10]:
my_array= np.arange(10)
print (my_array)

[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [11]:
array_2= np.full((3,3), True)
print (array_2)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Ejercicio 4
Extrae todos los impares de `my_array`

In [17]:
print(my_array)
mask=my_array %2 != 0 
print(my_array[mask])



[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [3]:
print(my_array)
mask=my_array %2 == 1 
my_array[my_array %2 == 1 ]

NameError: name 'my_array' is not defined

## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [35]:
array_copia= my_array.copy()
mask = array_copia %2 !=0
array_copia[mask]=-1
print(array_copia)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [34]:
array_copia= my_array.copy()
print (array_copia)
mask=my_array %2 != 0 
print(mask)
print(np.where(array_copia %2 != 0, -1, array_copia))

[0 1 2 3 4 5 6 7 8 9]
[False  True False  True False  True False  True False  True]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [42]:
my_array=my_array.reshape(2,5)
print(my_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Ejercicio 8
Concatena los siguientes arrays verticalmente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate((a,b))
#pruebo de esta manera

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack([a,b])
#pruebo de esta otra manera

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [45]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa la función `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [47]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [48]:
help(np.concatenate)

Help on _ArrayFunctionDispatcher in module numpy:

concatenate(...)
    concatenate(
        (a1, a2, ...),
        axis=0,
        out=None,
        dtype=None,
        casting="same_kind"
    )
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento de `my_array`
3. Accede al último elemento de `my_array`
4. Imprime por pantalla los numeros del 1 al 7 de `my_array`

In [50]:
my_array= np.arange(10)
print(my_array)
new_array= my_array * 10
print(new_array)

[0 1 2 3 4 5 6 7 8 9]
[ 0 10 20 30 40 50 60 70 80 90]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [51]:
my_matrix = [[1,2,3],
            [4,5,6],
            [7,8,9]]

## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [53]:
print(np.arange(start=1,stop=50,step=3))

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


## Ejercicio 15
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [58]:
print(np.random.randint(5,20, size = (4,5,3)))

[[[ 8  6  6]
  [10 17  7]
  [ 9 14  8]
  [15 19  8]
  [15 15  7]]

 [[11  6 11]
  [13 12 19]
  [17 18  9]
  [12  5 19]
  [ 5  5 19]]

 [[11  5 15]
  [12 10 10]
  [ 5  6  5]
  [16 11 11]
  [ 9  7 16]]

 [[14  7  5]
  [18 15 18]
  [19  5 15]
  [ 8  6 12]
  [19  8  5]]]


## Ejercicio 16
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [72]:
my_matrix = np.full((10,1), False)
#print(my_matrix)
my_matrix=my_matrix.reshape(2,5)
print(my_matrix)



[[False False False False False]
 [False False False False False]]


## Ejercicio 17
Dado el siguiente array

```Python
x = np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuánta es la longitud cada dimensión?

In [81]:
x = np.random.randint(10, 20, size = (5,2,6))
print(x)
print(x.size) #número de elementos
print (x.ndim) #dimensiones
print (x.shape)

[[[16 18 14 15 10 10]
  [19 15 15 19 19 10]]

 [[10 14 15 13 19 12]
  [16 18 19 18 17 12]]

 [[13 19 16 10 12 11]
  [18 10 15 19 16 18]]

 [[16 19 17 17 12 13]
  [11 15 10 11 17 16]]

 [[10 16 16 19 15 11]
  [19 12 17 16 13 10]]]
60
3
(5, 2, 6)
