![imagen](./img/ejercicios.png)

In [4]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [5]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
print(my_array[::-2])

[9 7 5 3 1]


In [7]:
print(my_array[my_array % 2 == 1][::-1])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [8]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [10]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
print(my_array[2::-1])

[2 1 0]


In [12]:
print(sorted(my_array[:3],reverse=True))

[np.int64(2), np.int64(1), np.int64(0)]


In [13]:
np.take(my_array, [2,1,0])

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [14]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [15]:
my_matrix.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [16]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [17]:
print(my_matrix[::-1,::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [ ]:
print(np.flip(my_matrix)) #lo invierte

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [19]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [20]:
print(my_matrix[:2,:2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [21]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [22]:
print(my_matrix[::2,::2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [23]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [24]:
print(my_matrix[:3,::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [25]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [ ]:
x == "Loro" #nos enera una máscara

array([ True, False, False,  True, False])

In [27]:
x[x == "Loro"]

array(['Loro', 'Loro'], dtype='<U5')

In [28]:
print(np.where(x== "Loro")[0])

[0 3]


In [29]:
print(np.where(x == "Loro")[0])

[0 3]


In [30]:
x[np.where(x == "Loro")]

array(['Loro', 'Loro'], dtype='<U5')

In [31]:
# np.where(x == "Loro", x, np.nan)

## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [2]:
x = np.arange(20).reshape(2,5,2)
print(x)

NameError: name 'np' is not defined

In [33]:
print(x.ndim)
print(x.shape)
print(x.size)

3
(2, 5, 2)
20


In [34]:
x = np.arange(20).reshape(10,2)
print(x)
m1,m2 = np.vsplit(x,[5])
print()
print(m1)
print()
print(m2)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [45]:
zeros=np.zeros((10))
print (zeros)
print(zeros.nbytes)
zeros[3]=1
print (zeros)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
80
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [ ]:
vector= np.arange(10,50)
print (vector)
vector_inver=vector[::-1] #se puede poner un flip y lo hace automático
print(vector_inver)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [58]:
valores=[1,2,0,0,4,0]
valores=np.nonzero(valores)
print (valores)

#he encontrado esto pero me da las posiciones no los valores que no son 0 por lo que no me sirve

(array([0, 1, 4]),)


In [ ]:
(np.where(j !=0[0]))

## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [61]:
matriz_aleatoria=(np.random.randint(2,60, size = (10,10)))
print(matriz_aleatoria)
print (np.min(matriz_aleatoria), np.max(matriz_aleatoria))

[[ 5 25 50 10 57 50 58 39 14 56]
 [37 49 33 39 13 24 54 26 52 42]
 [34 33 14 37 23 42 10  2  5 20]
 [54 33 16  2 18 30 33  9 46 34]
 [55 53 59 36 24 37 39 45 55 37]
 [ 9 52 43 56  8 34 49 34 43 19]
 [56 41 29 36  9 48 59 25 16 14]
 [45 53 56 33 59 50 17 40  2  4]
 [35 28 33 12 45 26 58 15  6 50]
 [16 17 47 31 28 24 42  2 51  2]]
2 59


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [64]:
vector_aleatorio=(np.random.randint(2,60, size = (30)))
print(vector_aleatorio)
print(vector_aleatorio.mean())

[44 40 29 20 25 43 18  3 18 45 45  5 47 43 33 51 11 42 20 51 36 41 25 57
 41 49 34 44  8 38]
33.53333333333333


## Ejercicio 15
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [ ]:
matriz_aleatoria_2=(np.random.randint(2,60, size = (5,5)))
print (matriz_aleatoria_2)
print (matriz_aleatoria_2.mean())
print (matriz_aleatoria_2.std())
matriz_normalizada= matriz_aleatoria_2 - 26.96 / 20.05
print(matriz_normalizada)
#Esto no puede ser así porque obviamente camia cada vez que ejecuto el código

[[27 30 53 21 31]
 [37  6 20 33 34]
 [43 32  7 47  9]
 [12  2 13 27 46]
 [14 15 48 45 21]]
26.92
14.612104571210814
[[25.6553616 28.6553616 51.6553616 19.6553616 29.6553616]
 [35.6553616  4.6553616 18.6553616 31.6553616 32.6553616]
 [41.6553616 30.6553616  5.6553616 45.6553616  7.6553616]
 [10.6553616  0.6553616 11.6553616 25.6553616 44.6553616]
 [12.6553616 13.6553616 46.6553616 43.6553616 19.6553616]]


In [ ]:
matriz_aleatoria_2=(np.random.randint(2,60, size = (5,5))) - (matriz_aleatoria_2.mean()) / (matriz_aleatoria_2.std())
print (matriz_aleatoria_2)
#me he inventado esto pero no sé

[[53.1576918 35.1576918  1.1576918 17.1576918 48.1576918]
 [46.1576918 49.1576918 38.1576918 40.1576918 57.1576918]
 [23.1576918 52.1576918  9.1576918 49.1576918 36.1576918]
 [46.1576918  7.1576918 34.1576918 35.1576918 39.1576918]
 [33.1576918  5.1576918  1.1576918 36.1576918 18.1576918]]


## Ejercicio 16
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [ ]:
secuencia= np.arange(11)
print (secuencia)
mask= (secuencia >=3) & (secuencia <=8)
secuencia[mask]=-1
print (secuencia)
print(np.where(secuencia == -1, False, secuencia)) #no sé a qué se refiere con negar, esto es lo que se me ocurre :)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
[ 0  1  2  0  0  0  0  0  0  9 10]
